### ISSUE TITLE
Not sure if player seek is working...

### ISSUE THREAD

**Issue by JBI1971** [jcsaaddupuy/python-xbmc#8]
I have a video file. If I run the following on 3.4 (from PyCharm), it pauses, then plays again, without any change in position 
Apologies if I am missing something basic.

print(xbmc.Player.GetActivePlayers())
xbmc.Player.PlayPause([PLAYER_VIDEO])
xbmc.Player.Seek(1,2000)
xbmc.Player.PlayPause([PLAYER_VIDEO])

Response is: 
{'jsonrpc': '2.0', 'id': 0, 'result': [{'playerid': 1, 'type': 'video'}]}

Process finished with exit code 0

**Comment by jcsaaddupuy** [comment]
Hi.
I have to say that I don't know even know if/how seeking is working ;)
This lib is very generic and just translate python code + parameters to Kodi jsonrpc calls.

By looking at the doc of [Player.Seek](http://kodi.wiki/view/JSON-RPC_API/v6#Player.Seek), it take a Player.Id as first parameter in the same way as [Player.PlayPause](http://kodi.wiki/view/JSON-RPC_API/v6#Player.PlayPause)

Maybe you could try something like :

    xbmc.Player.Seek([PLAYER_VIDEO], value=2000)

Let me know if this works, if it's not the case I'll dig deeper.

**Comment by JBI1971** [comment]
Hi,
Thanks for your response.
I tried that briefly this morning, didn't seem to work, but  I had to go to
work so could not look in detail.

Unfortunately the json-rpc api documentation is not incredibly clear, so it
often does seem to require a bit of additional work to figure out syntax,
so it may just be I am making a basic error
I will try looking again this evening.
Thanks for your work on the library,
Jack

**Comment by JBI1971** [comment]
Hi,
I got it to work, thank you. The original JSON-RPC API v6 documentation on
Player.Seek parameters was not very clear, but I found an actual example of
how to structure it on another site.
The following seeks 10 minutes into the video.

xbmc.Player.Seek({"playerid":1,"value":{ "hours":0, "minutes":10, "seconds":0}})

I may try to compile a list of example requests for general use.
Thanks again.

**Comment by jcsaaddupuy** [comment]
Nice !

You'll be able to use the PLAYER_VIDEO instead of the raw value 1.

Something I forgot about how parameters are parsed : you can either a use dict as parameters (as in your solution) or use kwargs arguments directly, like :

    xbmc.Player.Seek(playerid=PLAYER_VIDEO,value={ "hours":0, "minutes":10, "seconds":0}) 

If you haven't see it yet, their are others examples on how to use xbmcjson in [jcsaaddupuy/xbmc-client](https://github.com/jcsaaddupuy/xbmc-client) (see [xbmc_client.py#L88](https://github.com/jcsaaddupuy/xbmc-client/blob/master/src/xbmc_client/xbmc_client.py#L88))
